name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install tox

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: tox -e cov-ci
